services:
  fmi_db:
    image: mariadb:latest
    container_name: fmi_db
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  php_app:
    build: .
    container_name: fmi_php
    ports:
      - "8000:8000"
    depends_on:
      - fmi_db
    networks:
      - app_network
    volumes:
      - .:/var/www/html

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge
