services:
  FMI_DB:
    image: postgres:latest
    container_name: fmi_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: always

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
