services:
  fmi_db:
    image: postgres:latest
    container_name: fmi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  php_app:
    build: .
    container_name: fmi_php
    ports:
      - "8000:8000"
    depends_on:
      - fmi_db
    networks:
      - app_network
    volumes:
      - .:/var/www/html

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
